[versions]
kotlin = "2.2.20"
kotlinx-serialization = "1.9.0"
jna = "5.17.0"
compose = "1.9.0" # par estável com Kotlin 2.2.20 (Fase 2)

[libraries]
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose" }
